apiVersion: v1
kind: ConfigMap
metadata:
  name: royalafg-poker
data:
  config.yaml: |
    http_port: 7654
    rabbitmq_url: royalafg-rabbitmq.default.svc.cluster.local:5672
    matchmaker_signing_key: matchmakingkey
---
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: royalafg-poker-autoscaler
spec:
  fleetName: royalafg-poker
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 1
      maxReplicas: 5 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: royalafg-poker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: royalafg-poker
  namespace: default
subjects:
- kind: ServiceAccount
  name: royalafg-poker
roleRef:
  kind: ClusterRole
  name: agones-sdk
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: royalafg-poker
  labels:
    name: "royalafg-poker"
    game: "poker"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: "royalafg-poker"
        game: "poker"
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7654
          protocol: TCP
      health:
        initialDelaySeconds: 20
        periodSeconds: 60
        failureThreshold: 10
          
      template:
        metadata:
          labels:
            app: royalafg-poker-gameserver
          annotations:
            "consul.hashicorp.com/connect-inject": "false"
        
            "vault.hashicorp.com/agent-limits-cpu": "200m"
            "vault.hashicorp.com/agent-limits-mem": "100Mi"
            "vault.hashicorp.com/agent-requests-cpu": "20m"
            "vault.hashicorp.com/agent-requests-mem": "25Mi"

            "vault.hashicorp.com/agent-inject": "true"
            "vault.hashicorp.com/agent-inject-secret-poker.yaml": "kv-v2/poker"
            "vault.hashicorp.com/agent-inject-template-poker.yaml": |
              {{- with secret "kv-v2/poker" -}}
              matchmaker_signing_key: {{.Data.data.signing_key}}
              {{- end}}
            "vault.hashicorp.com/agent-inject-secret-rabbitmq.yaml": "rabbitmq/creds/royalafg"
            "vault.hashicorp.com/agent-inject-template-rabbitmq.yaml": |
              {{- with secret "rabbitmq/creds/royalafg" -}}
              rabbitmq_username: {{.Data.username}}
              rabbitmq_password: {{.Data.password}}
              {{- end}}
            "vault.hashicorp.com/role": "poker-role"
        spec:
          serviceAccountName: royalafg-poker
          containers:
            - name: royalafg-poker
              image: docker.io/johnnys318/royalafg_poker:latest
              # env:
              #   - name: POKER_RABBITMQ_USERNAME
              #     valueFrom:
              #       secretKeyRef:
              #         key: username
              #         name: royalafg-rabbitmq-default-user
              #   - name: POKER_RABBITMQ_PASSWORD
              #     valueFrom:
              #       secretKeyRef:
              #         key: password
              #         name: royalafg-rabbitmq-default-user
              volumeMounts:
                - name: royalafg-poker-config
                  mountPath: "/etc/royalafg-poker"
              resources:
                requests:
                  memory: 10Mi
                  cpu: 10m
                limits:
                  memory: 50Mi
                  cpu: 25m                       
          volumes:
            - name: royalafg-poker-config
              configMap:
                name: royalafg-poker
        